name: ecobiz_mobile_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  device_info_plus: ^3.2.2
  firebase_messaging: ^11.2.7
  fl_chart: ^0.50.1
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_downloader: ^1.7.2
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  get: 4.6.1
  get_directory_native:
    git: https://github.com/irwan75/get_directory_native.git
  get_it: ^7.2.0
  google_fonts: 2.2.0
  http: ^0.13.4
  image_picker: ^0.8.4+6
  intl: ^0.17.0
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/illustration/
    
  fonts:
    - family: Averta
      fonts:
        - asset: assets/fonts/Averta-Regular.otf
          weight: 400
        - asset: assets/fonts/Averta-Bold.otf
          weight: 700
    - family: openSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
